### PR TITLE
Delete Filter cmd and update find cmd

### LINKED ISSUE #113: bug(filter): Does not filter based on Hackathon correctly
## Context

Image

This is what was listed when I ran `filter h/AI Challenge 2024`

## Expected behaviour
Should not have listed people not interested or participating in `AI Challenge 2024`

## To Reproduce
Run `filter h/AI Challenge 2024`

### PR DESCRIPTION
**Pull request by thejus03**
Fixes #113

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -38,6 +38,28 @@ public static boolean containsWordIgnoreCase(String sentence, String word) {
...
+     *   Ignores case and allows partial matching.
+     *   <br>examples:<pre>
+     *       containsSubstringIgnoreCase("ABc def", "abc") == true
+     *       containsSubstringIgnoreCase("ABc def", "AB") == true
+     *       containsSubstringIgnoreCase("NUSHack 2024", "NUS") == true
+     *       containsSubstringIgnoreCase("AI Hackathon", "AI Hack") == true
+     *       </pre>
+     * @param text cannot be null
+     * @param substring cannot be null, cannot be empty
+     */
```
Comment (Rihiz) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: very clear javadoc comments
